# 1. ส่วนนี้สั่งรัน Web App ของคุณ และแยกร่างเป็น 2 ตัวทันที! (โชว์ความเทพ)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: krittaphat054/my-first-webapp:latest # โหลด Image ล่าสุดของคุณลงมา
        ports:
        - containerPort: 3000

---
# 2. ส่วนนี้ทำหน้าที่เป็น Load Balancer เปิดประตูบ้านให้เราเข้าเว็บได้
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: LoadBalancer # สั่งเปิดประตูออกสู่โลกภายนอก (localhost)
  selector:
    app: webapp
  ports:
  - port: 8080 # เราจะเข้าเว็บผ่านพอร์ต 8080
    targetPort: 3000